#!/usr/bin/env node
// Build the bestiary: one page holding every entity, its sigil, its class name,
// its dead Aspect, and every post it has appeared in.
//
//   node scripts/bestiary.mjs
//
// Writes lore/bestiary.md (tracked, links into the repo) and docs/bestiary.png
// (a rendered plate wall). Both regenerate from source, so the bestiary grows by
// itself as posts ship rather than by anyone remembering to update a list.
//
// Sources, all of them already the truth somewhere else:
//   lore/cast.md      the roster, traits and origin lines
//   lore/pantheon.md  the succession table, which Aspect died for which
//   lessons/*/        cast: frontmatter, which is the appearance record
//   design-kit.mjs    the drawing and the sigil
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import { portrait, sigil, castIds, castMeta, T } from "./design-kit.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// Series accent per entity, so the bestiary shows each one in the colour it ships in.
const ACCENT = {
  "the-messenger": "#4ec9b0", "the-concussed-witness": "#7c5cff",
  "the-second-witness": "#7c5cff", "the-archivist": "#6f86c9",
  "doze-the-jailer": "#ff9f45", "the-recomposer": "#4aa3ff",
  "the-understudy": "#c48bff", "the-ferryman": "#5ec6d8",
  "the-vault-keeper": "#7EE787", "the-fleet": "#4ec9b0",
  "the-backlog": "#ff7b9c", "null": "#ff6b81", "the-hunter": "#8b98a8",
  "the-borrowed-hand": "#d9a441",
};

// --- appearances, straight off the lessons -----------------------------------
const lessons = readdirSync(join(ROOT, "lessons")).filter((d) => /^\d{4}-\d{2}-\d{2}-/.test(d)).sort();
const appearances = {};
for (const d of lessons) {
  const p = join(ROOT, "lessons", d, "lesson.md");
  if (!existsSync(p)) continue;
  const src = readFileSync(p, "utf8");
  const title = (src.match(/^title:\s*"?([^"\n]+)"?/m) || [])[1] || d;
  const iter = (src.match(/^loop_iteration:\s*(\d+)/m) || [])[1] || "";
  const line = (src.match(/^cast:\s*\[([^\]]*)\]/m) || [])[1] || "";
  for (const raw of line.split(",")) {
    const id = raw.trim();
    if (!id) continue;
    (appearances[id] ||= []).push({ dir: d, title, iter: Number(iter) || 0 });
  }
}

// --- dead Aspects, parsed out of the pantheon succession table ---------------
const dead = {};
if (existsSync(join(ROOT, "lore", "pantheon.md"))) {
  for (const row of readFileSync(join(ROOT, "lore", "pantheon.md"), "utf8").split("\n")) {
    // Split on pipes rather than pattern-matching the whole row. The living
    // Aspect cell can itself contain parentheses (`Migration(23, 24)`), which a
    // \(([^)]+)\) group silently fails on, and silently is the bad kind.
    const cells = row.split("|").map((c) => c.trim());
    if (cells.length < 5 || !/^\*\*/.test(cells[3])) continue;
    const livingName = (cells[3].match(/\*\*([^*]+)\*\*/) || [])[1];
    if (!livingName) continue;
    const id = livingName.trim().toLowerCase().replace(/\s+/g, "-");
    if (!/none/i.test(cells[2])) dead[id] = cells[2].replace(/\*\*/g, "").trim();
  }
}

const ids = castIds();
const sorted = [...ids].sort((a, b) => (appearances[b]?.length || 0) - (appearances[a]?.length || 0));

// --- lore/bestiary.md --------------------------------------------------------
const seen = sorted.filter((id) => appearances[id]?.length);
const unseen = sorted.filter((id) => !appearances[id]?.length);
const row = (id) => {
  const m = castMeta(id);
  const apps = appearances[id] || [];
  const list = apps
    .sort((a, b) => a.iter - b.iter)
    .map((a) => `[${a.iter || "?"}](../lessons/${a.dir}/lesson.md)`)
    .join(" · ");
  return `| **${m.name}** | \`${m.className}\` | ${apps.length} | ${list || "not yet"} | ${dead[id] ? dead[id] : "—"} |`;
};

const md = `---
title: The Loopdown — Bestiary
type: generated
status: living
---

# Bestiary

Generated by \`scripts/bestiary.mjs\`. Do not hand-edit: it rebuilds from
[cast.md](cast.md), [pantheon.md](pantheon.md) and the \`cast:\` frontmatter in every lesson,
so it is a record rather than a claim.

**${ids.length} entities. ${seen.length} have appeared. ${Object.values(appearances).flat().length} appearances across ${lessons.length} posts.**

Numbers in the appearances column are loop iterations, and link to the lesson.

## On stage

| Entity | Aspect | Posts | Iterations | Dead Aspect it replaced |
|---|---|---:|---|---|
${seen.map(row).join("\n")}

## Waiting in the wings

| Entity | Aspect | Posts | Iterations | Dead Aspect it replaced |
|---|---|---:|---|---|
${unseen.map(row).join("\n")}

---

Each entity's mark is its **Aspect string hashed into geometry** (\`sigil()\` in
\`scripts/design-kit.mjs\`), so the sigil is the class name in another alphabet and changes if
the class does. The rendered wall is at [\`docs/bestiary.png\`](../docs/bestiary.png).
`;
writeFileSync(join(ROOT, "lore", "bestiary.md"), md);

// --- docs/bestiary.png: the plate wall ---------------------------------------
const cell = (id) => {
  const m = castMeta(id);
  const a = ACCENT[id] || "#7c5cff";
  const apps = appearances[id] || [];
  return `<div class="c" style="--a:${a}">
    <div class="art">${portrait(id, a)}</div>
    <div class="foot">
      <div class="sig">${sigil(m.className, a, { size: 66, stroke: 1.7 })}</div>
      <div class="tx">
        <div class="nm">${m.name}</div>
        <div class="cls">${m.className}</div>
      </div>
      <div class="n">${apps.length || "—"}</div>
    </div>
    ${dead[id] ? `<div class="dead">was ${dead[id].replace(/`/g, "")}</div>` : ""}
  </div>`;
};

const html = `<style>
 *{margin:0;padding:0;box-sizing:border-box}
 body{background:#06080B;font-family:-apple-system,'SF Pro Display',sans-serif;color:${T.ink};padding:52px 44px}
 h1{font-size:52px;font-weight:800;letter-spacing:-.03em}
 .sub{color:${T.inkFaint};font-family:${T.mono};font-size:20px;margin:12px 0 40px}
 .g{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}
 .c{border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:20px 20px 16px;
    background:linear-gradient(160deg,rgba(255,255,255,.03),transparent);position:relative}
 .c .art{height:250px;display:grid;place-items:center}
 .c .art svg{max-height:250px;width:auto}
 .foot{display:flex;align-items:center;gap:12px;border-top:1px solid color-mix(in srgb,var(--a) 30%,transparent);padding-top:14px;margin-top:8px}
 .sig{width:52px;flex:0 0 52px}.sig svg{width:100%;height:auto;display:block}
 .tx{flex:1;min-width:0}
 .nm{font-size:19px;font-weight:800;letter-spacing:.05em;color:var(--a)}
 .cls{font-family:${T.mono};font-size:14px;color:${T.inkFaint};margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
 .n{font-family:${T.mono};font-size:24px;font-weight:700;color:var(--a);opacity:.9}
 .dead{font-family:${T.mono};font-size:13px;color:${T.inkFaint};margin-top:8px;opacity:.75}
</style>
<h1>Bestiary</h1>
<div class="sub">${ids.length} entities · ${seen.length} on stage · ${Object.values(appearances).flat().length} appearances across ${lessons.length} posts · the number is posts</div>
<div class="g">${sorted.map(cell).join("")}</div>`;

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1680, height: 1200 }, deviceScaleFactor: 1.25 });
await page.setContent(html, { waitUntil: "load" });
mkdirSync(join(ROOT, "docs"), { recursive: true });
writeFileSync(join(ROOT, "docs", "bestiary.png"), await page.screenshot({ fullPage: true }));
await browser.close();

console.log(`bestiary: ${ids.length} entities, ${seen.length} on stage, ${Object.values(appearances).flat().length} appearances`);
console.log(`  -> lore/bestiary.md`);
console.log(`  -> docs/bestiary.png`);
